// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjTZ7P3fnASO1Q61x2iyO_AfeWBY8OZiw',
    appId: '1:195195207193:web:bb4a1c66514f5fbafcf488',
    messagingSenderId: '195195207193',
    projectId: 'selfevaluator-001',
    authDomain: 'selfevaluator-001.firebaseapp.com',
    storageBucket: 'selfevaluator-001.firebasestorage.app',
    measurementId: 'G-H1VYZZL0QF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl5BH5NwvWtp0155JbK4NhHy-buNBGqZg',
    appId: '1:195195207193:android:d0d14d7e29f4c75bfcf488',
    messagingSenderId: '195195207193',
    projectId: 'selfevaluator-001',
    storageBucket: 'selfevaluator-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvATijN32DjdvFb1npa4vQyah1gsHSmf4',
    appId: '1:195195207193:ios:ef1f6e1959009f12fcf488',
    messagingSenderId: '195195207193',
    projectId: 'selfevaluator-001',
    storageBucket: 'selfevaluator-001.firebasestorage.app',
    iosBundleId: 'com.example.selfEvaluator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvATijN32DjdvFb1npa4vQyah1gsHSmf4',
    appId: '1:195195207193:ios:ef1f6e1959009f12fcf488',
    messagingSenderId: '195195207193',
    projectId: 'selfevaluator-001',
    storageBucket: 'selfevaluator-001.firebasestorage.app',
    iosBundleId: 'com.example.selfEvaluator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjTZ7P3fnASO1Q61x2iyO_AfeWBY8OZiw',
    appId: '1:195195207193:web:aa56f7ae6a16f41efcf488',
    messagingSenderId: '195195207193',
    projectId: 'selfevaluator-001',
    authDomain: 'selfevaluator-001.firebaseapp.com',
    storageBucket: 'selfevaluator-001.firebasestorage.app',
    measurementId: 'G-J5WSEF9R6N',
  );
}
